// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rhyme-game/DarkLuxury.tsx": () => import("../components/mockups/rhyme-game/DarkLuxury.tsx"),
  "./components/mockups/rhyme-game/NeonArcade.tsx": () => import("../components/mockups/rhyme-game/NeonArcade.tsx"),
  "./components/mockups/rhyme-game/RhymeGameFlow.tsx": () => import("../components/mockups/rhyme-game/RhymeGameFlow.tsx"),
  "./components/mockups/rhyme-game/StreetEditorial.tsx": () => import("../components/mockups/rhyme-game/StreetEditorial.tsx")
};
